// Copyright (c) technicianted. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0--rc2
// source: inline.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	proto "k9s-autoscaler/pkg/proto"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines configuration for inline autoscaler storage provider adapter. It embeds
// autoscaler proto configs.
// see: examples/intree/sim.yaml for an example.
type InlineStorageConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of defined autoscalers.
	Autoscalers []*proto.Autoscaler `protobuf:"bytes,1,rep,name=autoscalers,proto3" json:"autoscalers,omitempty"`
}

func (x *InlineStorageConfig) Reset() {
	*x = InlineStorageConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inline_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InlineStorageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineStorageConfig) ProtoMessage() {}

func (x *InlineStorageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_inline_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineStorageConfig.ProtoReflect.Descriptor instead.
func (*InlineStorageConfig) Descriptor() ([]byte, []int) {
	return file_inline_proto_rawDescGZIP(), []int{0}
}

func (x *InlineStorageConfig) GetAutoscalers() []*proto.Autoscaler {
	if x != nil {
		return x.Autoscalers
	}
	return nil
}

var File_inline_proto protoreflect.FileDescriptor

var file_inline_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25,
	0x6b, 0x39, 0x73, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x58, 0x0a, 0x13, 0x49, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x41, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x6f,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x6b, 0x39, 0x73, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x52, 0x0b,
	0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x73, 0x42, 0x32, 0x5a, 0x30, 0x6b,
	0x39, 0x73, 0x2d, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inline_proto_rawDescOnce sync.Once
	file_inline_proto_rawDescData = file_inline_proto_rawDesc
)

func file_inline_proto_rawDescGZIP() []byte {
	file_inline_proto_rawDescOnce.Do(func() {
		file_inline_proto_rawDescData = protoimpl.X.CompressGZIP(file_inline_proto_rawDescData)
	})
	return file_inline_proto_rawDescData
}

var file_inline_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_inline_proto_goTypes = []interface{}{
	(*InlineStorageConfig)(nil), // 0: k9sautoscaler.providers.storage.proto.InlineStorageConfig
	(*proto.Autoscaler)(nil),    // 1: k9sautoscaler.proto.Autoscaler
}
var file_inline_proto_depIdxs = []int32{
	1, // 0: k9sautoscaler.providers.storage.proto.InlineStorageConfig.autoscalers:type_name -> k9sautoscaler.proto.Autoscaler
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inline_proto_init() }
func file_inline_proto_init() {
	if File_inline_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inline_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InlineStorageConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inline_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inline_proto_goTypes,
		DependencyIndexes: file_inline_proto_depIdxs,
		MessageInfos:      file_inline_proto_msgTypes,
	}.Build()
	File_inline_proto = out.File
	file_inline_proto_rawDesc = nil
	file_inline_proto_goTypes = nil
	file_inline_proto_depIdxs = nil
}
