// Copyright (c) technicianted. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0--rc2
// source: azuredeployment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Target config for an Azure Cognitive Services deployment.
type AzureDeploymentTargetConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Full Azure resource URI for scaling.
	ResourceURI string `protobuf:"bytes,1,opt,name=ResourceURI,proto3" json:"ResourceURI,omitempty"`
	// Deployment name to target for scaling.
	DeploymentName string `protobuf:"bytes,2,opt,name=DeploymentName,proto3" json:"DeploymentName,omitempty"`
}

func (x *AzureDeploymentTargetConfig) Reset() {
	*x = AzureDeploymentTargetConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_azuredeployment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AzureDeploymentTargetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureDeploymentTargetConfig) ProtoMessage() {}

func (x *AzureDeploymentTargetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_azuredeployment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureDeploymentTargetConfig.ProtoReflect.Descriptor instead.
func (*AzureDeploymentTargetConfig) Descriptor() ([]byte, []int) {
	return file_azuredeployment_proto_rawDescGZIP(), []int{0}
}

func (x *AzureDeploymentTargetConfig) GetResourceURI() string {
	if x != nil {
		return x.ResourceURI
	}
	return ""
}

func (x *AzureDeploymentTargetConfig) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

// Azure Cognitive Services deployment scaler configuration.
// Depending on the type of scaling operation, if update operation is used,
// it may take as long as a few minutes to complete. Make sure that you both
// have the autoscaler controller run multiple workers, and set the correct
// behavior accordingly.
type AzureDeploymentConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AzureDeploymentConfig) Reset() {
	*x = AzureDeploymentConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_azuredeployment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AzureDeploymentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureDeploymentConfig) ProtoMessage() {}

func (x *AzureDeploymentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_azuredeployment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureDeploymentConfig.ProtoReflect.Descriptor instead.
func (*AzureDeploymentConfig) Descriptor() ([]byte, []int) {
	return file_azuredeployment_proto_rawDescGZIP(), []int{1}
}

var File_azuredeployment_proto protoreflect.FileDescriptor

var file_azuredeployment_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x6b, 0x39, 0x73, 0x61, 0x75, 0x74, 0x6f,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73,
	0x2e, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67,
	0x0a, 0x1b, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x0a,
	0x0b, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x52, 0x49, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x52, 0x49, 0x12,
	0x26, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x41, 0x7a, 0x75, 0x72, 0x65,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x42, 0x32, 0x5a, 0x30, 0x6b, 0x39, 0x73, 0x2d, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73,
	0x2f, 0x73, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_azuredeployment_proto_rawDescOnce sync.Once
	file_azuredeployment_proto_rawDescData = file_azuredeployment_proto_rawDesc
)

func file_azuredeployment_proto_rawDescGZIP() []byte {
	file_azuredeployment_proto_rawDescOnce.Do(func() {
		file_azuredeployment_proto_rawDescData = protoimpl.X.CompressGZIP(file_azuredeployment_proto_rawDescData)
	})
	return file_azuredeployment_proto_rawDescData
}

var file_azuredeployment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_azuredeployment_proto_goTypes = []interface{}{
	(*AzureDeploymentTargetConfig)(nil), // 0: k9sautoscaler.providers.scaling.proto.AzureDeploymentTargetConfig
	(*AzureDeploymentConfig)(nil),       // 1: k9sautoscaler.providers.scaling.proto.AzureDeploymentConfig
}
var file_azuredeployment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_azuredeployment_proto_init() }
func file_azuredeployment_proto_init() {
	if File_azuredeployment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_azuredeployment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AzureDeploymentTargetConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_azuredeployment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AzureDeploymentConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_azuredeployment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_azuredeployment_proto_goTypes,
		DependencyIndexes: file_azuredeployment_proto_depIdxs,
		MessageInfos:      file_azuredeployment_proto_msgTypes,
	}.Build()
	File_azuredeployment_proto = out.File
	file_azuredeployment_proto_rawDesc = nil
	file_azuredeployment_proto_goTypes = nil
	file_azuredeployment_proto_depIdxs = nil
}
