// Copyright (c) technicianted. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0--rc2
// source: aoai.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AzureOAIMetricConfig_Metric int32

const (
	AzureOAIMetricConfig_None AzureOAIMetricConfig_Metric = 0
	// Measures the percentage of rate of 429 request to total rate of
	// requests.
	// Useful for Provisioned Managed offers.
	AzureOAIMetricConfig_Percent429Rate AzureOAIMetricConfig_Metric = 1
)

// Enum value maps for AzureOAIMetricConfig_Metric.
var (
	AzureOAIMetricConfig_Metric_name = map[int32]string{
		0: "None",
		1: "Percent429Rate",
	}
	AzureOAIMetricConfig_Metric_value = map[string]int32{
		"None":           0,
		"Percent429Rate": 1,
	}
)

func (x AzureOAIMetricConfig_Metric) Enum() *AzureOAIMetricConfig_Metric {
	p := new(AzureOAIMetricConfig_Metric)
	*p = x
	return p
}

func (x AzureOAIMetricConfig_Metric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AzureOAIMetricConfig_Metric) Descriptor() protoreflect.EnumDescriptor {
	return file_aoai_proto_enumTypes[0].Descriptor()
}

func (AzureOAIMetricConfig_Metric) Type() protoreflect.EnumType {
	return &file_aoai_proto_enumTypes[0]
}

func (x AzureOAIMetricConfig_Metric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AzureOAIMetricConfig_Metric.Descriptor instead.
func (AzureOAIMetricConfig_Metric) EnumDescriptor() ([]byte, []int) {
	return file_aoai_proto_rawDescGZIP(), []int{0, 0}
}

type AzureOAIMetricConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Target Azure resource URI.
	ResourceURI string `protobuf:"bytes,1,opt,name=resourceURI,proto3" json:"resourceURI,omitempty"`
	// Taget AOAI deployment name.
	DeploymentName string `protobuf:"bytes,2,opt,name=deploymentName,proto3" json:"deploymentName,omitempty"`
}

func (x *AzureOAIMetricConfig) Reset() {
	*x = AzureOAIMetricConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aoai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AzureOAIMetricConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureOAIMetricConfig) ProtoMessage() {}

func (x *AzureOAIMetricConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aoai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureOAIMetricConfig.ProtoReflect.Descriptor instead.
func (*AzureOAIMetricConfig) Descriptor() ([]byte, []int) {
	return file_aoai_proto_rawDescGZIP(), []int{0}
}

func (x *AzureOAIMetricConfig) GetResourceURI() string {
	if x != nil {
		return x.ResourceURI
	}
	return ""
}

func (x *AzureOAIMetricConfig) GetDeploymentName() string {
	if x != nil {
		return x.DeploymentName
	}
	return ""
}

// Convience composed, ready to use metrics for Azure OpenAI services.
type AzureOAIConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AzureMonitorConfig *AzureMonitorConfig `protobuf:"bytes,1,opt,name=azure_monitor_config,json=azureMonitorConfig,proto3" json:"azure_monitor_config,omitempty"`
}

func (x *AzureOAIConfig) Reset() {
	*x = AzureOAIConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aoai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AzureOAIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureOAIConfig) ProtoMessage() {}

func (x *AzureOAIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aoai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureOAIConfig.ProtoReflect.Descriptor instead.
func (*AzureOAIConfig) Descriptor() ([]byte, []int) {
	return file_aoai_proto_rawDescGZIP(), []int{1}
}

func (x *AzureOAIConfig) GetAzureMonitorConfig() *AzureMonitorConfig {
	if x != nil {
		return x.AzureMonitorConfig
	}
	return nil
}

var File_aoai_proto protoreflect.FileDescriptor

var file_aoai_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x6f, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x6b, 0x39,
	0x73, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x14, 0x41, 0x7a, 0x75, 0x72,
	0x65, 0x4f, 0x41, 0x49, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x52, 0x49, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55,
	0x52, 0x49, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x06, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x12,
	0x0a, 0x0e, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x34, 0x32, 0x39, 0x52, 0x61, 0x74, 0x65,
	0x10, 0x01, 0x22, 0x7d, 0x0a, 0x0e, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x4f, 0x41, 0x49, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x6b, 0x0a, 0x14, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x5f, 0x6d, 0x6f,
	0x6e, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x39, 0x2e, 0x6b, 0x39, 0x73, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x7a, 0x75, 0x72, 0x65,
	0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x12, 0x61,
	0x7a, 0x75, 0x72, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x42, 0x32, 0x5a, 0x30, 0x6b, 0x39, 0x73, 0x2d, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aoai_proto_rawDescOnce sync.Once
	file_aoai_proto_rawDescData = file_aoai_proto_rawDesc
)

func file_aoai_proto_rawDescGZIP() []byte {
	file_aoai_proto_rawDescOnce.Do(func() {
		file_aoai_proto_rawDescData = protoimpl.X.CompressGZIP(file_aoai_proto_rawDescData)
	})
	return file_aoai_proto_rawDescData
}

var file_aoai_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aoai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aoai_proto_goTypes = []interface{}{
	(AzureOAIMetricConfig_Metric)(0), // 0: k9sautoscaler.providers.metrics.proto.AzureOAIMetricConfig.Metric
	(*AzureOAIMetricConfig)(nil),     // 1: k9sautoscaler.providers.metrics.proto.AzureOAIMetricConfig
	(*AzureOAIConfig)(nil),           // 2: k9sautoscaler.providers.metrics.proto.AzureOAIConfig
	(*AzureMonitorConfig)(nil),       // 3: k9sautoscaler.providers.metrics.proto.AzureMonitorConfig
}
var file_aoai_proto_depIdxs = []int32{
	3, // 0: k9sautoscaler.providers.metrics.proto.AzureOAIConfig.azure_monitor_config:type_name -> k9sautoscaler.providers.metrics.proto.AzureMonitorConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aoai_proto_init() }
func file_aoai_proto_init() {
	if File_aoai_proto != nil {
		return
	}
	file_azuremonitor_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_aoai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AzureOAIMetricConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aoai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AzureOAIConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aoai_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aoai_proto_goTypes,
		DependencyIndexes: file_aoai_proto_depIdxs,
		EnumInfos:         file_aoai_proto_enumTypes,
		MessageInfos:      file_aoai_proto_msgTypes,
	}.Build()
	File_aoai_proto = out.File
	file_aoai_proto_rawDesc = nil
	file_aoai_proto_goTypes = nil
	file_aoai_proto_depIdxs = nil
}
