// Copyright (c) technicianted. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0--rc2
// source: azuremonitor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AzureMonitorConfig_SelectorLabels int32

const (
	// Target Azure resource URI. Required selector.
	AzureMonitorConfig_ResourceURI AzureMonitorConfig_SelectorLabels = 0
	// Metric Azure namespace. Required selector.
	AzureMonitorConfig_MetricNamespace AzureMonitorConfig_SelectorLabels = 1
	// Filter values using expressions. Optional selector.
	AzureMonitorConfig_Filter AzureMonitorConfig_SelectorLabels = 2
)

// Enum value maps for AzureMonitorConfig_SelectorLabels.
var (
	AzureMonitorConfig_SelectorLabels_name = map[int32]string{
		0: "ResourceURI",
		1: "MetricNamespace",
		2: "Filter",
	}
	AzureMonitorConfig_SelectorLabels_value = map[string]int32{
		"ResourceURI":     0,
		"MetricNamespace": 1,
		"Filter":          2,
	}
)

func (x AzureMonitorConfig_SelectorLabels) Enum() *AzureMonitorConfig_SelectorLabels {
	p := new(AzureMonitorConfig_SelectorLabels)
	*p = x
	return p
}

func (x AzureMonitorConfig_SelectorLabels) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AzureMonitorConfig_SelectorLabels) Descriptor() protoreflect.EnumDescriptor {
	return file_azuremonitor_proto_enumTypes[0].Descriptor()
}

func (AzureMonitorConfig_SelectorLabels) Type() protoreflect.EnumType {
	return &file_azuremonitor_proto_enumTypes[0]
}

func (x AzureMonitorConfig_SelectorLabels) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AzureMonitorConfig_SelectorLabels.Descriptor instead.
func (AzureMonitorConfig_SelectorLabels) EnumDescriptor() ([]byte, []int) {
	return file_azuremonitor_proto_rawDescGZIP(), []int{0, 0}
}

// Configuration for Azure Monitor based metrics provider.
// Authentication is handled using default Azure credential mechanism.
// See: https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication
// It is important that the metrics query returns exactly 1 time series to be usable
// in autoscaling.
type AzureMonitorConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AzureMonitorConfig) Reset() {
	*x = AzureMonitorConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_azuremonitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AzureMonitorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMonitorConfig) ProtoMessage() {}

func (x *AzureMonitorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_azuremonitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMonitorConfig.ProtoReflect.Descriptor instead.
func (*AzureMonitorConfig) Descriptor() ([]byte, []int) {
	return file_azuremonitor_proto_rawDescGZIP(), []int{0}
}

var File_azuremonitor_proto protoreflect.FileDescriptor

var file_azuremonitor_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x6b, 0x39, 0x73, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x12, 0x41,
	0x7a, 0x75, 0x72, 0x65, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x22, 0x42, 0x0a, 0x0e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4c, 0x61, 0x62,
	0x65, 0x6c, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55,
	0x52, 0x49, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x10, 0x02, 0x42, 0x32, 0x5a, 0x30, 0x6b, 0x39, 0x73, 0x2d, 0x61, 0x75, 0x74,
	0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_azuremonitor_proto_rawDescOnce sync.Once
	file_azuremonitor_proto_rawDescData = file_azuremonitor_proto_rawDesc
)

func file_azuremonitor_proto_rawDescGZIP() []byte {
	file_azuremonitor_proto_rawDescOnce.Do(func() {
		file_azuremonitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_azuremonitor_proto_rawDescData)
	})
	return file_azuremonitor_proto_rawDescData
}

var file_azuremonitor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_azuremonitor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_azuremonitor_proto_goTypes = []interface{}{
	(AzureMonitorConfig_SelectorLabels)(0), // 0: k9sautoscaler.providers.metrics.proto.AzureMonitorConfig.SelectorLabels
	(*AzureMonitorConfig)(nil),             // 1: k9sautoscaler.providers.metrics.proto.AzureMonitorConfig
}
var file_azuremonitor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_azuremonitor_proto_init() }
func file_azuremonitor_proto_init() {
	if File_azuremonitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_azuremonitor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AzureMonitorConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_azuremonitor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_azuremonitor_proto_goTypes,
		DependencyIndexes: file_azuremonitor_proto_depIdxs,
		EnumInfos:         file_azuremonitor_proto_enumTypes,
		MessageInfos:      file_azuremonitor_proto_msgTypes,
	}.Build()
	File_azuremonitor_proto = out.File
	file_azuremonitor_proto_rawDesc = nil
	file_azuremonitor_proto_goTypes = nil
	file_azuremonitor_proto_depIdxs = nil
}
