// Copyright (c) technicianted. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0--rc2
// source: sim.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define a load entry for a given duration.
type MetricLoad struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Duration to maintain load.
	Timespan *durationpb.Duration `protobuf:"bytes,1,opt,name=timespan,proto3" json:"timespan,omitempty"`
	// Simulated total load.
	Load float64 `protobuf:"fixed64,2,opt,name=load,proto3" json:"load,omitempty"`
}

func (x *MetricLoad) Reset() {
	*x = MetricLoad{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricLoad) ProtoMessage() {}

func (x *MetricLoad) ProtoReflect() protoreflect.Message {
	mi := &file_sim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricLoad.ProtoReflect.Descriptor instead.
func (*MetricLoad) Descriptor() ([]byte, []int) {
	return file_sim_proto_rawDescGZIP(), []int{0}
}

func (x *MetricLoad) GetTimespan() *durationpb.Duration {
	if x != nil {
		return x.Timespan
	}
	return nil
}

func (x *MetricLoad) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

// Define a metrics configuration for an autoscaler.
type AutoscalerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutoscalerName      string `protobuf:"bytes,1,opt,name=autoscaler_name,json=autoscalerName,proto3" json:"autoscaler_name,omitempty"`
	AutoscalerNamespace string `protobuf:"bytes,2,opt,name=autoscaler_namespace,json=autoscalerNamespace,proto3" json:"autoscaler_namespace,omitempty"`
	// Assumed max load per instance to be able to calculate load percentage.
	MaxLoadPerInstance float64 `protobuf:"fixed64,3,opt,name=max_load_per_instance,json=maxLoadPerInstance,proto3" json:"max_load_per_instance,omitempty"`
	// One or more load schedule entries.
	Load []*MetricLoad `protobuf:"bytes,4,rep,name=load,proto3" json:"load,omitempty"`
}

func (x *AutoscalerConfig) Reset() {
	*x = AutoscalerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoscalerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoscalerConfig) ProtoMessage() {}

func (x *AutoscalerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoscalerConfig.ProtoReflect.Descriptor instead.
func (*AutoscalerConfig) Descriptor() ([]byte, []int) {
	return file_sim_proto_rawDescGZIP(), []int{1}
}

func (x *AutoscalerConfig) GetAutoscalerName() string {
	if x != nil {
		return x.AutoscalerName
	}
	return ""
}

func (x *AutoscalerConfig) GetAutoscalerNamespace() string {
	if x != nil {
		return x.AutoscalerNamespace
	}
	return ""
}

func (x *AutoscalerConfig) GetMaxLoadPerInstance() float64 {
	if x != nil {
		return x.MaxLoadPerInstance
	}
	return 0
}

func (x *AutoscalerConfig) GetLoad() []*MetricLoad {
	if x != nil {
		return x.Load
	}
	return nil
}

// Simulated metrics config.
// see: examples/intree/sim.yaml for an example.
type SimConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetricName        string              `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	AutoscalersConfig []*AutoscalerConfig `protobuf:"bytes,2,rep,name=autoscalers_config,json=autoscalersConfig,proto3" json:"autoscalers_config,omitempty"`
}

func (x *SimConfig) Reset() {
	*x = SimConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sim_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimConfig) ProtoMessage() {}

func (x *SimConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sim_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimConfig.ProtoReflect.Descriptor instead.
func (*SimConfig) Descriptor() ([]byte, []int) {
	return file_sim_proto_rawDescGZIP(), []int{2}
}

func (x *SimConfig) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *SimConfig) GetAutoscalersConfig() []*AutoscalerConfig {
	if x != nil {
		return x.AutoscalersConfig
	}
	return nil
}

// Autoscaler metric config. Not used.
type SimMetricConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SimMetricConfig) Reset() {
	*x = SimMetricConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sim_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimMetricConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimMetricConfig) ProtoMessage() {}

func (x *SimMetricConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sim_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimMetricConfig.ProtoReflect.Descriptor instead.
func (*SimMetricConfig) Descriptor() ([]byte, []int) {
	return file_sim_proto_rawDescGZIP(), []int{3}
}

// Dummy scaling target config. Not used for this provider.
type SimScalingTargetConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SimScalingTargetConfig) Reset() {
	*x = SimScalingTargetConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sim_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimScalingTargetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimScalingTargetConfig) ProtoMessage() {}

func (x *SimScalingTargetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sim_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimScalingTargetConfig.ProtoReflect.Descriptor instead.
func (*SimScalingTargetConfig) Descriptor() ([]byte, []int) {
	return file_sim_proto_rawDescGZIP(), []int{4}
}

var File_sim_proto protoreflect.FileDescriptor

var file_sim_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x6b, 0x39, 0x73,
	0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x57, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x6f, 0x61, 0x64,
	0x12, 0x35, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xe8, 0x01, 0x0a, 0x10,
	0x41, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x27, 0x0a, 0x0f, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x75, 0x74, 0x6f, 0x73,
	0x63, 0x61, 0x6c, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x14, 0x61, 0x75, 0x74,
	0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x15,
	0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x12, 0x6d, 0x61, 0x78,
	0x4c, 0x6f, 0x61, 0x64, 0x50, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x45, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x31, 0x2e,
	0x6b, 0x39, 0x73, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4c, 0x6f, 0x61, 0x64,
	0x52, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x09, 0x53, 0x69, 0x6d, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x66, 0x0a, 0x12, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x72, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x37, 0x2e, 0x6b, 0x39, 0x73, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x11, 0x61, 0x75, 0x74, 0x6f,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x11, 0x0a,
	0x0f, 0x53, 0x69, 0x6d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0x18, 0x0a, 0x16, 0x53, 0x69, 0x6d, 0x53, 0x63, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x31, 0x5a, 0x2f, 0x6b, 0x39,
	0x73, 0x2d, 0x61, 0x75, 0x74, 0x6f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x6d, 0x65, 0x72, 0x69, 0x63,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sim_proto_rawDescOnce sync.Once
	file_sim_proto_rawDescData = file_sim_proto_rawDesc
)

func file_sim_proto_rawDescGZIP() []byte {
	file_sim_proto_rawDescOnce.Do(func() {
		file_sim_proto_rawDescData = protoimpl.X.CompressGZIP(file_sim_proto_rawDescData)
	})
	return file_sim_proto_rawDescData
}

var file_sim_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sim_proto_goTypes = []interface{}{
	(*MetricLoad)(nil),             // 0: k9sautoscaler.providers.metrics.proto.MetricLoad
	(*AutoscalerConfig)(nil),       // 1: k9sautoscaler.providers.metrics.proto.AutoscalerConfig
	(*SimConfig)(nil),              // 2: k9sautoscaler.providers.metrics.proto.SimConfig
	(*SimMetricConfig)(nil),        // 3: k9sautoscaler.providers.metrics.proto.SimMetricConfig
	(*SimScalingTargetConfig)(nil), // 4: k9sautoscaler.providers.metrics.proto.SimScalingTargetConfig
	(*durationpb.Duration)(nil),    // 5: google.protobuf.Duration
}
var file_sim_proto_depIdxs = []int32{
	5, // 0: k9sautoscaler.providers.metrics.proto.MetricLoad.timespan:type_name -> google.protobuf.Duration
	0, // 1: k9sautoscaler.providers.metrics.proto.AutoscalerConfig.load:type_name -> k9sautoscaler.providers.metrics.proto.MetricLoad
	1, // 2: k9sautoscaler.providers.metrics.proto.SimConfig.autoscalers_config:type_name -> k9sautoscaler.providers.metrics.proto.AutoscalerConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sim_proto_init() }
func file_sim_proto_init() {
	if File_sim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricLoad); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sim_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoscalerConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sim_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sim_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimMetricConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sim_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimScalingTargetConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sim_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sim_proto_goTypes,
		DependencyIndexes: file_sim_proto_depIdxs,
		MessageInfos:      file_sim_proto_msgTypes,
	}.Build()
	File_sim_proto = out.File
	file_sim_proto_rawDesc = nil
	file_sim_proto_goTypes = nil
	file_sim_proto_depIdxs = nil
}
